version: '3'

services:
  smartcarapi:
    image: smartcarapi
    container_name: smartcar_api
    build:
      context: ./SmartCarApi
      dockerfile: Dockerfile
  smartcarui:
    image: smartcarui
    container_name: smartcar_ui
    build:
      context: ./SmartCarUi
      dockerfile: Dockerfile
  smartcaridentity:
    image: smartcaridentity
    container_name: smartcar_identity
    build:
      context: ./SmartCarIdentity
      dockerfile: Dockerfile
  smartcardb:
    image: "alackner/smartcardb"
    container_name: smartcar_db
    ports:
      - "3306:3306"
