version: '3'

services:
  smartcarapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
  smartcarui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
  smartcaridentity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16